//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotCyToolboxPlugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntityGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotCyToolboxPlugins.EntityGroups", typeof(EntityGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to businessunit
        ///channelpropertygroup
        ///transactioncurrency
        ///documenttemplate
        ///emailserverprofile
        ///fieldsecurityprofile
        ///principalobjectattributeaccess
        ///goal
        ///metric
        ///mailbox
        ///mailboxtrackingfolder
        ///organization
        ///personaldocumenttemplate
        ///position
        ///principalsyncattributemap
        ///goalrollupquery
        ///role
        ///syncattributemappingprofile
        ///team
        ///systemuser
        ///usersettings
        ///prvDocumentGeneration
        ///prvGoOffline
        ///prvPrint
        ///prvSyncToOutlook
        ///prvExportToExcel
        ///prvMailMerge
        ///prvActOnBehalfOfAnotherUser
        ///prvActOnBehalfOfExternalParty
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessManagement {
            get {
                return ResourceManager.GetString("BusinessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account
        ///actioncard
        ///actioncardusersettings
        ///activitypointer
        ///businessunitnewsarticle
        ///applicationfile
        ///category
        ///connection
        ///connectionrole
        ///contact
        ///customerrelationship
        ///import
        ///dataperformance
        ///sharepointdocumentlocation
        ///recommendeddocument
        ///duplicaterule
        ///emailsignature
        ///template
        ///feedback
        ///postfollow
        ///importfile
        ///interactionforemail
        ///dtk_ticketinglanguage
        ///lead
        ///mailmergetemplate
        ///mobileofflineprofile
        ///annotation
        ///opportunity
        ///customeropportunityrole
        ///post
        ///queue
        ///relationshiprole
        ///report
        ///savedorgin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Core_Records {
            get {
                return ResourceManager.GetString("Core_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appmodule
        ///attributemap
        ///customcontrol
        ///customcontroldefaultconfig
        ///customcontrolresource
        ///entitymap
        ///hierarchyrule
        ///importjob
        ///pluginassembly
        ///plugintracelog
        ///workflow
        ///complexcontrol
        ///processsession
        ///publisher
        ///relationshiprole
        ///sdkmessage
        ///sdkmessageprocessingstep
        ///sdkmessageprocessingstepimage
        ///sdkmessageprocessingstepsecureconfig
        ///serviceendpoint
        ///solution
        ///systemapplicationmetadata
        ///savedqueryvisualization
        ///systemform
        ///asyncoperation
        ///theme
        ///userapplicationmetadata
        ///savedquery
        ///webresource
        ///prvActivat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customization {
            get {
                return ResourceManager.GetString("Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campaign
        ///list
        ///prvConfigureInternetMarketing
        ///prvUseInternetMarketing
        ///prvAllowQuickCampaign.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salesorder
        ///competitor
        ///invoice
        ///product
        ///dynamicproperty
        ///dynamicpropertyassociation
        ///dynamicpropertyinstance
        ///dynamicpropertyoptionsetitem
        ///quote
        ///salesliterature
        ///territory
        ///prvOverridePriceEngineOrder
        ///prvOverridePriceEngineInvoice
        ///prvOverridePriceEngineOpportunity
        ///prvOverridePriceEngineQuote
        ///prvQOIOverrideDelete.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kbarticle
        ///kbarticlecomment
        ///kbarticletemplate
        ///bookableresource
        ///bookableresourcebooking
        ///bookableresourcebookingheader
        ///bookableresourcecategory
        ///bookableresourcecategoryassn
        ///bookableresourcecharacteristic
        ///bookableresourcegroup
        ///bookableresourcebookingexchangesyncidmapping
        ///bookingstatus
        ///incident
        ///incidentresolution
        ///characteristic
        ///contract
        ///contractdetail
        ///contracttemplate
        ///knowledgearticle
        ///knowledgearticleviews
        ///ratingmodel
        ///ratingvalue
        ///prvApproveKnowledgeArticle
        ///prvPublishKnowledgeArticle
        ///prvPu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar
        ///entitlement
        ///entitlementtemplate
        ///equipment
        ///knowledgebaserecord
        ///convertrule
        ///routingrule
        ///service
        ///site
        ///sla
        ///slakpiinstance
        ///prvBrowseAvailability
        ///prvCreateOwnCalendar
        ///prvReadOwnCalendar
        ///prvWriteOwnCalendar
        ///prvDeleteOwnCalendar
        ///prvWriteHolidayScheduleCalendar
        ///prvControlDecrementTerm
        ///prvSearchAvailability.
        /// </summary>
        internal static string ServiceManagement {
            get {
                return ResourceManager.GetString("ServiceManagement", resourceCulture);
            }
        }
    }
}
