//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotCyToolboxPlugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FetchXMLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchXMLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotCyToolboxPlugins.FetchXMLQueries", typeof(FetchXMLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;privilege&quot; &gt;
        ///    &lt;attribute name=&quot;canbebasic&quot; /&gt;
        ///    &lt;attribute name=&quot;canbedeep&quot; /&gt;
        ///    &lt;attribute name=&quot;privilegeid&quot; /&gt;
        ///    &lt;attribute name=&quot;accessright&quot; /&gt;
        ///    &lt;attribute name=&quot;canbelocal&quot; /&gt;
        ///    &lt;attribute name=&quot;canbeglobal&quot; /&gt;
        ///    &lt;attribute name=&quot;canbeentityreference&quot; /&gt;
        ///    &lt;attribute name=&quot;canbeparententityreference&quot; /&gt;
        ///    &lt;attribute name=&quot;name&quot; /&gt;
        ///    &lt;link-entity name=&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllSecurityPriviledges {
            get {
                return ResourceManager.GetString("GetAllSecurityPriviledges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;roleprivileges&quot; &gt;
        ///    &lt;attribute name=&quot;privilegedepthmask&quot; /&gt;
        ///    &lt;attribute name=&quot;privilegeid&quot; /&gt;
        ///    &lt;attribute name=&quot;roleprivilegeid&quot; /&gt;
        ///    &lt;attribute name=&quot;roleid&quot; /&gt;
        ///    &lt;filter&gt;
        ///      &lt;condition attribute=&quot;roleid&quot; operator=&quot;in&quot; &gt;
        ///        {0}
        ///      &lt;/condition&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetPriviledgesForRoles {
            get {
                return ResourceManager.GetString("GetPriviledgesForRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;role&quot; &gt;
        ///    &lt;attribute name=&quot;name&quot; /&gt;
        ///    &lt;attribute name=&quot;iscustomizable&quot; /&gt;
        ///    &lt;attribute name=&quot;businessunitid&quot; /&gt;
        ///    &lt;attribute name=&quot;roleid&quot; /&gt;
        ///    &lt;attribute name=&quot;componentstate&quot; /&gt;
        ///    &lt;attribute name=&quot;roleidunique&quot; /&gt;
        ///    &lt;attribute name=&quot;ismanaged&quot; /&gt;
        ///    &lt;attribute name=&quot;solutionid&quot; /&gt;
        ///    &lt;attribute name=&quot;modifiedon&quot; /&gt;
        ///    &lt;attribute name=&quot;parentroleid&quot; /&gt;
        ///    &lt;attr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSecurityRoles {
            get {
                return ResourceManager.GetString("GetSecurityRoles", resourceCulture);
            }
        }
    }
}
